apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vonkp36qg-nodejs
  janus-idp.io/tekton: vonkp36qg-nodejs
  backstage.io/kubernetes-id: vonkp36qg-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vonkp36qg-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
