apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vonkp36qg-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vonkp36qg-nodejs 
  name: vonkp36qg-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: vonkp36qg-nodejs 
